;(function () {

    const resultData = {
        //最終結果用
        'motivation':{
            'param':'r7Nt',
            'motivation':{
                'motivation':{
                    'param':'aC43',
                    'text':'G6nr',
                },
                'carefree':{
                    'param':'Zi4j',
                    'text':'K6yT',
                },
                'ephemeral':{
                    'param':'T7a3',
                    'text':'Em7z',
                },
            },
            'carefree':{
                'motivation':{
                    'param':'Fn2J',
                    'text':'Lr2M',
                },
                'carefree':{
                    'param':'fM4x',
                    'text':'W8i9',
                },
                'ephemeral':{
                    'param':'eZ4f',
                    'text':'Sw8E',
                },
            },
            'ephemeral':{
                'motivation':{
                    'param':'e6EM',
                    'text':'rW2y',
                },
                'carefree':{
                    'param':'w6BG',
                    'text':'hX6W',
                },
                'ephemeral':{
                    'param':'p7Ce',
                    'text':'zE7n',
                },
            },
        },
        'carefree':{
            'param':'fU7P',
            'motivation':{
                'motivation':{
                    'param':'i9A3',
                    'text':'G6nr',
                },
                'carefree':{
                    'param':'Fy4H',
                    'text':'K6yT',
                },
                'ephemeral':{
                    'param':'V9dr',
                    'text':'Em7z',
                },
            },
            'carefree':{
                'motivation':{
                    'param':'p3FE',
                    'text':'Lr2M',
                },
                'carefree':{
                    'param':'f9UV',
                    'text':'W8i9',
                },
                'ephemeral':{
                    'param':'pR5A',
                    'text':'Sw8E',
                },
            },
            'ephemeral':{
                'motivation':{
                    'param':'vE84',
                    'text':'uX5F',
                },
                'carefree':{
                    'param':'x5Pc',
                    'text':'hX6W',
                },
                'ephemeral':{
                    'param':'Bw4y',
                    'text':'zE7n',
                },
            },
        },
        'ephemeral':{
            'param':'x5Mu',
            'motivation':{
                'motivation':{
                    'param':'N3pB',
                    'text':'G6nr',
                },
                'carefree':{
                    'param':'sP9k',
                    'text':'K6yT',
                },
                'ephemeral':{
                    'param':'b9Xq',
                    'text':'k6L2',
                },
            },
            'carefree':{
                'motivation':{
                    'param':'uT8H',
                    'text':'Lr2M',
                },
                'carefree':{
                    'param':'pR5H',
                    'text':'W8i9',
                },
                'ephemeral':{
                    'param':'s6Fu',
                    'text':'Sw8E',
                },
            },
            'ephemeral':{
                'motivation':{
                    'param':'J7tG',
                    'text':'uX5F',
                },
                'carefree':{
                    'param':'w4Sd',
                    'text':'hX6W',
                },
                'ephemeral':{
                    'param':'Jw4G',
                    'text':'zE7n',
                },
            },
        },
    };

    if (typeof window.DEMO_APP === "undefined") {
        window.DEMO_APP = {};
    }
    window.DEMO_APP.resultData = resultData;
})();